apiVersion: skuld/v1alpha1
kind: Observer
metadata:
  name: skuldd
  user: skuldd
spec:
  destination: /opt/skuldd
  project: skuldd
  source:
    path: /
    repoURL: git@github.com:lyssar/gameserver.git
    user: lyssar
    accessToken: YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL25KbExyNG1XaWNCMklvck1YMlM5TnFKcjJyeE9qb2paYWNPbDJOdGpJCmNvRllBMHZ5ckExb05KdlorL2s3dm9IQTdnQnJFUTgrUEdNMGlhVm02b0kKLS0tIDgvd1VJYTluMmxRMnlHVWs0cnRJK2xoYzV3R0dBeXVySjBiTk85ZHJ4ejgKhObWFgUX9dv1tpPHTdqAK/DK4gR2FlqICS3jewvJnqcua4R6YIQK7N2m5iVwiNmSt/wmtUJjMUtK0sHDnsfdxHR0e8a6togj
    targetRevision: HEAD
